### ISSUE TITLE
Move ccarh scores to op directories

### ISSUE THREAD

**Issue by craigsapp** [bel28kent/Mysterium#2]
It would be more convenient for `ccarh_kern` files to be moved into the opus directory sequence.  They are my files and I give you permission to do so :-) (Scriabin is too modern for CCARH, so in a technical sense then are not CCARH files in any case).

When you move files around in a repository (on the command-line), it is better to use "git mv" rather than plain "mv".  This allows keeping track of the editorial changes in the file; otherwise, when using plain `mv`, you are actually doing a copy and remove (which will cause another copy of the file with the new name to be added to the history of the repository, which in turn will make the repository storage larger than needed).

So here are the commands I am suggesting to move the `ccarh_kern` files (on the command line, of course):

```bash
git mv ccarh_kern/op11_no15.krn op11
git mv ccarh_kern/op11_no4.krn op11
git mv ccarh_kern/op2_no1.krn op-2
git mv ccarh_kern/op65_no2.krn op65
git mv ccarh_kern/op65_no3.krn op65
git mv ccarh_kern/op8_no1.krn op-8
git mv ccarh_kern/op8_no2.krn op-8
git mv ccarh_kern/op8_no3.krn op-8
git mv ccarh_kern/op8_no4.krn op-8
git mv ccarh_kern/op8_no5.krn op-8
git mv ccarh_kern/op8_no6.krn op-8
rmdir ccarh_kern
```

After this, type `git status` to see the changes, which should all be `rename`:

<img width="883" alt="Screenshot 2023-01-30 at 1 53 02 PM" src="https://user-images.githubusercontent.com/3487289/215603706-35681689-d25a-419b-a4a4-573a39aa648b.png">

And then upload as usual with `git commit` and `git push`.

**Comment by bel28kent** [comment]
Thank you for this suggestion. One issue here is that your files contain some information that mine don't, most importantly *MM information. I plan to add this information in a "second phase" of the corpus in which I will also add the symphonic works and do a review of the piano files. At that point I will also add the *MM information. I would like to keep the files separate until then, but will definitely change this when the time comes.

**Comment by craigsapp** [comment]
OK.  I should fix those files and send you the updates and then they can be merged.   They were created around 2004, which is now almost 20 years ago (12 years before VHV...).

**Comment by bel28kent** [comment]
@craigsapp 
I have decided to resolve this issue now to make working with the repo easier on the command line as I am starting to compile a list of issues with the encodings. I have also added a list of the files that you encoded to the README.
