### ISSUE TITLE
Opus directory names (single digits v. double digit ordering).

### ISSUE THREAD

**Issue by craigsapp** [bel28kent/Mysterium#3]
When you use `ls` on the command line, the opus directories are not in numeric order:

<img width="911" alt="Screenshot 2023-01-30 at 2 01 32 PM" src="https://user-images.githubusercontent.com/3487289/215605294-f910421b-57d3-4d76-bf49-ce9180be8fa8.png">

When using `ls -v` the ordering is somewhat better:

<img width="911" alt="Screenshot 2023-01-30 at 2 02 17 PM" src="https://user-images.githubusercontent.com/3487289/215605448-f3e5e6aa-1772-4f27-8c48-29113c12922a.png">

But 1-9 are listed after all of the two-digit opus numbers.

Unless you have a specific need for the names of the opus 1-9 directories/folders, it would be good to prefix the opus number with a 0.  This allow alphabetic and numeric sorting to be the same:

<img width="919" alt="Screenshot 2023-01-30 at 2 04 11 PM" src="https://user-images.githubusercontent.com/3487289/215605816-7e955303-6a15-409b-a136-1489d5485a87.png">

If you want to do this, then here are the terminal commands to do so:

```bash
git mv op-1 op01
git mv op-2 op02
git mv op-3 op03
git mv op-4 op04
git mv op-5 op05
git mv op-6 op06
git mv op-7 op07
git mv op-8 op08
git mv op-9 op09
```

Note that `git mv` is used rather than plain `mv`, with the reasons given in the previous issue (to avoid breaking the edit history of a file, and to not enlarge the history of the repository).

(the  `git status` to verify the changes are as expected and then `git commit` and `git push`).

**Comment by bel28kent** [comment]
Thank you for your suggestion. I was using the hyphen to force a natural sorting order (which works in my terminal), but I've followed your recommendation and added the double digits.

**Comment by craigsapp** [comment]
That is strange: The hyphen character comes before numbers in ASCII:

https://en.wikipedia.org/wiki/ASCII

I was listing the files in Red Hat linux in the above examples.   I tested in MacOS and it was behaving as you describe, which should be the preferred way of sorting.  In any case, using the "0" instead of "-" should force the sorting order to be the same in linux and MacOS.
