### ISSUE TITLE
Prefix filenames with with "scriabin-"

### ISSUE THREAD

**Issue by craigsapp** [bel28kent/Mysterium#5]
It would also be useful to prefix all Humdrum files with `scriabin-`.  This will allow mixing of files into a directory with other works by various composers who make use the similar opus number (and this prevent overwriting of files in such a case).

If this is agreeable to you, here is a bash command to do this:

```bash
for dir in op??
do
   (cd $dir;
      for file in op*.krn
      do
         git mv $file scriabin-$file
      done)
done
```

(do this command after issues #2, #3, and #4, since those changes have to be done in that order).

Then type `git status` to make sure everything went well (all changes should be "renamed:").  Then `git commit` and `git push`.

**Comment by bel28kent** [comment]
Done.
