### ISSUE TITLE
cresc. and decresc. have overlapping boundaries

### ISSUE THREAD

**Issue by bel28kent** [bel28kent/Mysterium#54]
In [scriabin-op11_no01.krn](https://github.com/bel28kent/Mysterium/blob/main/op11/scriabin-op11_no01.krn), the A5 is both the end of the cresc. that starts the note before and the start of the decresc. that ends on the note after. The token needs to be a `>` to start the decresc., but also a `[` or `]`. But neither works currently.

<img width="300" alt="Screen Shot 2024-05-05 at 12 37 12 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/4c37b25a-d4ad-4530-aeaf-1f597b9ec6b7">

<img width="1920" alt="Screen Shot 2024-05-05 at 12 38 40 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/1cef0bc3-2f30-401e-994f-2723572d6319">

**Comment by craigsapp** [comment]
Encode as separate cresc. wedge: `< [` and decresc. wedge: `> ]`, with the mid point pieces merged on the same token (preferably with a space beetween `[` and `>`:

<img width="697" alt="Screenshot 2024-05-05 at 11 21 53 AM" src="https://github.com/bel28kent/Mysterium/assets/3487289/bf924f8b-1626-409a-a1d3-8ad983ef1815">


[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqZHluYW0KOGRkTAkuCjhlZQk8CjhhYQlbID4KOGdnCV0KOGVlSgkuCiotCSotCg==)]

**Comment by bel28kent** [comment]
Fixed in 3353b45
