### ISSUE TITLE
edition uses "dim." and not "decresc."

### ISSUE THREAD

**Issue by bel28kent** [bel28kent/Mysterium#55]
The edition that I am encoding from uses "dim." instead of "decresc." It would be much faster if I could encode these using the unbalanced `>` that causes VHV to render the text instead of the bracket. Is it possible to specify "dim."? Since it is used consistently throughout the work, it would also be ideal if it could be specified once at top level, rather than locally every time it happens, as in `!!!RDF**dynam: > = !LO:TX:t="dim."`.

**Comment by craigsapp** [comment]
Here is a demo of what you want:

<img width="670" alt="Screenshot 2024-05-05 at 10 34 25 AM" src="https://github.com/bel28kent/Mysterium/assets/3487289/677b87eb-522f-4f61-a171-118a577bf29a">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqZHluYW0KKgkqCjJmCWZmCjJnCT4KPQk9CjJhCS4KMmcJcAo9PQk9PQoqLQkqLQohISFSREYqKmR5bmFtOiA+ID0gZGltLgo=)]


Where the control uses `RDF**dynam`,  close to what you are thinking of:

```
!!!RDF**dynam: > = dim.
```

**Comment by bel28kent** [comment]
Thanks!

For the pieces edited before this issue:
scriabin-op02_no02.krn in 2130d7c
scriabin-op09_no01.krn in 582668b
scriabin-op11_no01.krn in 8f913ba
scriabin-op11_no02.krn in 8baeff5
